[%
    T = {
        title = "Generate PIN codes",
        description = "Generate four-digit PIN codes as passwords for specified patron categories. (Local institution feature)",
        home = "Home",
        plugins = "Plugins",
        configuration = "Configuration",
        back = "Back",
        save = "Save configuration",
        config_label = "Patron categories for which to generate a four-digit PIN as password (comma-separated, e.g., HENKILO,LAPSI): ",
        upgrade_status = "Upgrade status",
        last_upgraded = "Plugin was last upgraded on this system on",
        never_upgraded = "Plugin has never been upgraded.",
        password_generated = "PIN password generated!",
        password_generation_failed = "Password generation failed!"
    }
%]
