[%
    T = {
        title = "Generoi PIN-koodit",
        description = "Luo määritetyille asiakastyypeille nelinumeroiset PIN-koodit salasanaksi. (Paikalliskannat)",
        home = "Etusivu",
        plugins = "Liitännäiset",
        configuration = "Määritys",
        back = "Takaisin",
        save = "Tallenna määritys",
        config_label = "Asiakastyypit, joille generoidaan nelinumeroinen salasana pilkuilla erotettuna (Esim. HENKILO,LAPSI): ",
        upgrade_status = "Päivityksen tila",
        last_upgraded = "Liitännäinen päivitettiin viimeksi tähän järjestelmään",
        never_upgraded = "Liitännäistä ei ole koskaan päivitetty.",
        password_generated = "PIN-salasana luotu!",
        password_generation_failed = "Salasanan luonti epäonnistui!"
    }
%]
