[%
    T = {
        title = "Generera PIN-koder",
        description = "Generera fyrsiffriga PIN-koder som lösenord för angivna kundkategorier. (Lokal institutionsfunktion)",
        home = "Hem",
        plugins = "Plugins",
        configuration = "Inställningar",
        back = "Tillbaka",
        save = "Spara inställningar",
        config_label = "Kundkategorier för vilka en fyrsiffrig PIN-kod ska genereras som lösenord (kommaseparerat, t.ex. HENKILO,LAPSI): ",
        upgrade_status = "Uppgraderingsstatus",
        last_upgraded = "Plugin uppgraderades senast på detta system den",
        never_upgraded = "Plugin har aldrig uppgraderats.",
        password_generated = "PIN-lösenord genererat!",
        password_generation_failed = "Lösenordsgenerering misslyckades!"
    }
%]
